name: inject_example_train
description: A more complex example of using package:inject

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  inject_annotation: ^1.0.0-alpha.3

dev_dependencies:
  build_runner: ^2.3.3
  build_test: ^2.1.5
  lints: ^2.0.1
  test: ^1.22.1
  inject_generator: ^1.0.0-alpha.2
