name: flutter_skeleton
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  inject_annotation: ^1.0.0-alpha.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  build_test: ^2.2.3
  flutter_lints: ^5.0.0
  inject_generator: ^1.0.0-alpha.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
