name: inject_dart

packages:
  - packages/**
  - examples/**

scripts:
  analyze:
    exec: dart analyze .
  fix:
    exec: dart fix --apply
  format:
    exec: dart format .
  clean-build:
    exec: dart run build_runner clean
    select-package:
      depends-on: build_runner
  build:
    exec: dart run build_runner clean && dart run build_runner build --delete-conflicting-outputs
    select-package:
      depends-on: build_runner
  test:
    run: melos run test:plain --no-select && melos run test:build-runner --no-select
  test:plain:
    run: melos exec -c 1 --fail-fast -- "dart test"
    select-package:
      no-depends-on: build_runner
      dir-exists: test
  test:build-runner:
    run: melos exec -c 1 --fail-fast -- "dart run build_runner clean && dart run build_runner test --delete-conflicting-outputs"
    select-package:
      depends-on: build_runner
      dir-exists: test
