name: inject_dart_workspace
publish_to: none
repository: https://github.com/ralph-bergmann/inject.dart
issue_tracker: https://github.com/ralph-bergmann/inject.dart/issues

environment:
  sdk: ^3.6.0

workspace:
  - examples/coffee
  - examples/example
  - examples/flutter_demo
  - examples/train
  - packages/inject_annotation
  - packages/inject_flutter
  - packages/inject_generator

dev_dependencies:
  melos: ^7.0.0-dev.7

melos:
  ide:
    intellij:
      enabled: false
  scripts:
    analyze:
      exec: fvm dart analyze .

    fix:
      exec: fvm dart fix --apply

    format:
      exec: fvm dart format -l 120 .

    pubupgrade:
      run: melos run pubupgrade:dart && melos run pubupgrade:flutter
    pubupgrade:dart:
      run: melos exec -c 1 --fail-fast -- "fvm dart pub upgrade"
      packageFilters:
        flutter: false
    pubupgrade:flutter:
      run: melos exec -c 1 --fail-fast -- "fvm flutter pub upgrade"
      packageFilters:
        flutter: true

    build:
      run: melos run build:dart && melos run build:flutter
    build:dart:
      run: melos exec -c 1 --fail-fast -- "fvm dart run build_runner clean && fvm dart run build_runner build -d"
      packageFilters:
        dependsOn: build_runner
        flutter: false
    build:flutter:
      run: melos exec -c 1 --fail-fast -- "fvm flutter pub run build_runner clean && fvm flutter pub run build_runner build -d"
      packageFilters:
        dependsOn: build_runner
        flutter: true

    test:
      run: melos run test:plain --no-select && melos run test:build-runner-dart --no-select && melos run test:build-runner-flutter --no-select
    test:plain:
      run: melos exec -c 1 --fail-fast -- "fvm dart test"
      packageFilters:
        noDependsOn: build_runner
        dirExists: test
        flutter: false
    test:build-runner-dart:
      run: melos exec -c 1 --fail-fast -- "fvm dart run build_runner clean && fvm dart run build_runner test -d"
      packageFilters:
        dependsOn: build_runner
        dirExists: test
        flutter: false
    test:build-runner-flutter:
      run: melos exec -c 1 --fail-fast -- "fvm dart run build_runner clean && fvm dart run build_runner build -d && fvm flutter test"
      packageFilters:
        dependsOn: build_runner
        dirExists: test
        flutter: true
