name: inject_dart_workspace
publish_to: none
repository: https://github.com/ralph-bergmann/inject.dart
issue_tracker: https://github.com/ralph-bergmann/inject.dart/issues

environment:
  sdk: ^3.6.0

workspace:
  - packages/inject_annotation
  - packages/inject_generator
  - examples/coffee
  - examples/flutter_skeleton
  - examples/train

dev_dependencies:
  melos: ^7.0.0-dev.7

melos:
  ide:
    intellij:
      enabled: false
