name: inject_flutter
description: >-
  Flutter extension for inject.dart that simplifies ViewModel injection and 
  lifecycle management to promote cleaner architecture in Flutter apps.
version: 1.0.1
documentation: https://ralph-bergmann.github.io/inject.dart/
repository: https://github.com/ralph-bergmann/inject.dart
issue_tracker: https://github.com/ralph-bergmann/inject.dart/issues
topics:
  - flutter
  - state-management
  - state
  - dependency-injection
  - architecture

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  inject_annotation: ^1.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
