name: inject_example_coffee
description: A simple example of using package:inject

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  inject_annotation: ^1.0.0-alpha.3

dev_dependencies:
  build_runner: ^2.4.14
  build_test: ^2.2.3
  lints: ^5.1.1
  test: ^1.24.9
  inject_generator: ^1.0.0-alpha.4
