name: inject_annotation
description: Compile-time constructor-based dependency injection for Dart and Flutter, similar to Dagger.
version: 1.0.0
documentation: https://ralph-bergmann.github.io/inject.dart/
repository: https://github.com/ralph-bergmann/inject.dart
issue_tracker: https://github.com/ralph-bergmann/inject.dart/issues
topics:
  - codegen
  - build-runner
  - dependency-injection
  - code-generation
  - generator

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  meta: ^1.15.0

dev_dependencies:
  lints: ^5.1.1
