name: inject_annotation
version: 1.0.0-alpha
description: Compile-time dependency injection for Dart
homepage: https://pub.dartlang.org/packages/inject

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
