name: inject_annotation
version: 1.0.0-alpha.4
description: Compile-time constructor-based dependency injection for Dart and Flutter, similar to Dagger.
repository: https://github.com/ralph-bergmann/inject.dart
issue_tracker: https://github.com/ralph-bergmann/inject.dart/issues

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  meta: ^1.10.0

dev_dependencies:
  lints: ^3.0.0
