# This file configures the static analysis results for your project (errors,
# warnings, and lints).
#
# This enables the 'recommended' set of lints from `package:lints`.
# This set helps identify many issues that may lead to problems when running
# or consuming Dart code, and enforces writing Dart using a single, idiomatic
# style and format.
#
# If you want a smaller set of lints you can change this to specify
# 'package:lints/core.yaml'. These are just the most critical lints
# (the recommended set includes the core lints).
# The core lints are also what is used by pub.dev for scoring packages.

include: package:lints/recommended.yaml

# Uncomment the following section to specify additional rules.

linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - avoid_returning_null_for_future
    - avoid_types_on_closure_parameters
    - cascade_invocations
    - comment_references
    - directives_ordering
    - eol_at_end_of_file
    - omit_local_variable_types
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_int_literals
    - prefer_null_aware_method_calls
    - prefer_relative_imports
    - prefer_single_quotes
    - require_trailing_commas
    - test_types_in_equals
    - throw_in_finally
    - unawaited_futures
    - unnecessary_await_in_return
    - use_super_parameters


analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.inject.dart"

# For more information about the core and recommended set of lints, see
# https://dart.dev/go/core-lints

# For additional information about configuring this file, see
# https://dart.dev/guides/language/analysis-options
