# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  summarize_builder:
    import: "package:inject_generator/inject_generator.dart"
    builder_factories: [ "summarizeBuilder" ]
    build_extensions: { ".dart": [ ".inject.summary" ] }
    auto_apply: dependents
    runs_before: [ ":generate_builder" ]
    build_to: cache
  generate_builder:
    import: "package:inject_generator/inject_generator.dart"
    builder_factories: [ "generateBuilder" ]
    build_extensions: { ".summary": [ ".inject.dart" ] }
    auto_apply: dependents
    build_to: source
#targets:
#  $default:
#    builders:
#      json_serializable:
#        options:
#          checked: true
