name: inject_generator
version: 1.0.0-alpha.3
description: Dev-time dependency for package:inject_annotation.
repository: https://github.com/ralph-bergmann/inject.dart
issue_tracker: https://github.com/ralph-bergmann/inject.dart/issues

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  analyzer: ^5.13.0
  build: ^2.4.1
  code_builder: ^4.7.0
  collection: ^1.17.2
  dart_style: ^2.3.2
  json_annotation: ^4.8.1
  logging: ^1.2.0
  meta: ^1.10.0
  path: ^1.8.3
  quiver: ^3.2.1
  source_gen: ^1.4.0
  stack_trace: ^1.11.1
  inject_annotation: ^1.0.0-alpha.3

dev_dependencies:
  build_test: ^2.2.1
  lints: ^3.0.0
  test: ^1.24.9

#  build_runner: ^2.3.3
#  json_serializable: ^6.6.1
