name: inject_generator
version: 1.0.0-alpha.3
description: Dev-time dependency for package:inject_annotation.
repository: https://github.com/ralph-bergmann/inject.dart
issue_tracker: https://github.com/ralph-bergmann/inject.dart/issues

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  analyzer: ^5.3.1
  build: ^2.3.1
  code_builder: ^4.4.0
  collection: ^1.17.0
  dart_style: ^2.2.4
  json_annotation: ^4.8.0
  logging: ^1.1.0
  meta: ^1.8.0
  path: ^1.8.2
  quiver: ^3.2.1
  source_gen: ^1.2.7
  stack_trace: ^1.11.0
  tuple: ^2.0.1
  inject_annotation: ^1.0.0-alpha.3

dev_dependencies:
  build_test: ^2.1.5
  lints: ^2.0.1
  test: ^1.22.1

#  build_runner: ^2.3.3
#  json_serializable: ^6.6.1
