name: inject_generator
description: Dev-time dependency for package:inject_annotation.
version: 2.0.0-pre1
documentation: https://ralph-bergmann.github.io/inject.dart/
repository: https://github.com/ralph-bergmann/inject.dart
issue_tracker: https://github.com/ralph-bergmann/inject.dart/issues
topics:
  - codegen
  - build-runner
  - dependency-injection
  - code-generation
  - generator

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  analyzer: ^7.3.0
  build: ^2.4.2
  code_builder: ^4.10.1
  collection: ^1.19.0
  dart_style: ^3.0.1
  inject_annotation: ^2.0.0-pre1
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.15.0
  path: ^1.9.0
  quiver: ^3.2.2
  source_gen: ^2.0.0
  stack_trace: ^1.12.0

dev_dependencies:
  build_test: ^2.2.3
  lints: ^5.1.1
  test: ^1.24.9

#  imports needed to regenerate json code
#  also enable build step in build.yaml
#  build_runner: ^2.4.15
#  json_serializable: ^6.9.5
