name: inject_generator
version: 1.0.0-alpha
description: Dev-time dependency for package:inject.
homepage: https://pub.dartlang.org/packages/inject

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  analyzer: ^5.3.1
  build: ^2.3.1
  code_builder: ^4.4.0
  collection: ^1.17.0
  dart_style: ^2.2.4
  logging: ^1.1.0
  meta: ^1.8.0
  path: ^1.8.2
  quiver: ^3.2.1
  stack_trace: ^1.11.0
  inject:
    path: ../inject
  tuple: ^2.0.1
  json_annotation: ^4.8.0

dev_dependencies:
  build_test: ^2.1.5
  lints: ^2.0.1
  test: ^1.22.1

  build_runner: ^2.3.3
  json_serializable: ^6.6.1
